# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class FraudAssessment(BaseModel):
    risk_score: typing.Optional[float] = None
    alert: typing.Optional[bool] = None
    reason: typing.Optional[str] = None
    confidence: typing.Optional[float] = None

class LoginEvent(BaseModel):
    user_id: typing.Optional[int] = None
    username: typing.Optional[str] = None
    ip_address: typing.Optional[str] = None
    user_agent: typing.Optional[str] = None
    timestamp: typing.Optional[str] = None
    event_type: typing.Optional[str] = None
    failed_attempts_5min: typing.Optional[int] = None
    failed_2fa_attempts_5min: typing.Optional[int] = None
    ip_changed: typing.Optional[bool] = None
    user_agent_changed: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
