"""
BAML client for interfacing with the fraud detection agent.

This module provides a wrapper around the BAML-generated client
for fraud detection analysis.
"""
import logging
from typing import Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class LoginEvent:
    """
    Input data structure for BAML fraud detection agent.

    Represents an authentication event with contextual information
    about recent user activity.
    """

    def __init__(
        self,
        user_id: int,
        username: str,
        ip_address: Optional[str],
        user_agent: Optional[str],
        timestamp: str,
        event_type: str,
        failed_attempts_5min: int,
        failed_2fa_attempts_5min: int,
        ip_changed: bool,
        user_agent_changed: bool
    ):
        self.user_id = user_id
        self.username = username
        self.ip_address = ip_address
        self.user_agent = user_agent
        self.timestamp = timestamp
        self.event_type = event_type
        self.failed_attempts_5min = failed_attempts_5min
        self.failed_2fa_attempts_5min = failed_2fa_attempts_5min
        self.ip_changed = ip_changed
        self.user_agent_changed = user_agent_changed


class BAMLFraudAssessment:
    """
    Output data structure from BAML fraud detection agent.

    Contains the risk assessment results from the AI agent.
    """

    def __init__(
        self,
        risk_score: float,
        alert: bool,
        reason: str,
        confidence: float
    ):
        self.risk_score = risk_score
        self.alert = alert
        self.reason = reason
        self.confidence = confidence


class BAMLClient:
    """
    Client for interfacing with BAML fraud detection agent.

    Handles communication with the BAML runtime and provides
    error handling and timeout management.
    """

    def __init__(self, timeout_ms: int = 5000):
        """
        Initialize BAML client.

        Args:
            timeout_ms: Timeout for BAML agent calls in milliseconds
        """
        self.timeout_ms = timeout_ms
        self._client = None
        self._initialized = False

        try:
            # Try to import BAML generated client
            # This will be generated by BAML CLI from the .baml schema
            from baml_client import b
            self._client = b
            self._initialized = True
            logger.info("BAML client initialized successfully")
        except ImportError as e:
            logger.warning(f"BAML client not available: {e}")
            logger.warning("Fraud detection will fall back to rule-based analysis")
        except Exception as e:
            logger.error(f"Error initializing BAML client: {e}", exc_info=True)

    def is_available(self) -> bool:
        """
        Check if BAML client is available and initialized.

        Returns:
            True if BAML client is ready to use, False otherwise
        """
        return self._initialized and self._client is not None

    async def analyze_fraud(self, event: LoginEvent) -> Optional[BAMLFraudAssessment]:
        """
        Analyze an authentication event for fraud using BAML agent.

        Args:
            event: LoginEvent with authentication details and context

        Returns:
            BAMLFraudAssessment if successful, None if BAML unavailable or error occurs
        """
        if not self.is_available():
            logger.warning("BAML client not available for fraud analysis")
            return None

        try:
            # Call BAML agent with timeout
            logger.debug(f"Calling BAML fraud detection for user {event.user_id}")

            # Call the BAML-generated function
            # The actual implementation depends on BAML code generation
            # Note: timeout is configured in BAML client initialization
            result = await self._client.FraudCheck(event)

            # Convert BAML result to our assessment format
            assessment = BAMLFraudAssessment(
                risk_score=float(result.risk_score),
                alert=bool(result.alert),
                reason=str(result.reason),
                confidence=float(result.confidence)
            )

            logger.info(
                f"BAML fraud analysis complete for user {event.user_id}: "
                f"risk_score={assessment.risk_score:.2f}, confidence={assessment.confidence:.2f}"
            )

            return assessment

        except TimeoutError:
            logger.warning(
                f"BAML fraud analysis timed out after {self.timeout_ms}ms "
                f"for user {event.user_id}"
            )
            return None
        except Exception as e:
            logger.error(
                f"Error during BAML fraud analysis for user {event.user_id}: {e}",
                exc_info=True
            )
            return None

    def analyze_fraud_sync(self, event: LoginEvent) -> Optional[BAMLFraudAssessment]:
        """
        Synchronous wrapper for fraud analysis.

        This is a convenience method for synchronous contexts.
        Uses asyncio.run internally.

        Args:
            event: LoginEvent with authentication details and context

        Returns:
            BAMLFraudAssessment if successful, None if BAML unavailable or error occurs
        """
        if not self.is_available():
            return None

        try:
            import asyncio
            return asyncio.run(self.analyze_fraud(event))
        except Exception as e:
            logger.error(f"Error in synchronous BAML call: {e}", exc_info=True)
            return None


# Global BAML client instance
_baml_client: Optional[BAMLClient] = None


def get_baml_client(timeout_ms: int = 5000) -> BAMLClient:
    """
    Get or create the global BAML client instance.

    Args:
        timeout_ms: Timeout for BAML agent calls in milliseconds

    Returns:
        BAMLClient instance
    """
    global _baml_client
    if _baml_client is None:
        _baml_client = BAMLClient(timeout_ms=timeout_ms)
    return _baml_client
