# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class AuthEvent(BaseModel):
    event_type: typing.Optional[str] = None
    ip_address: typing.Optional[str] = None
    user_agent: typing.Optional[str] = None
    timestamp: typing.Optional[str] = None
    success: typing.Optional[bool] = None

class FraudAssessment(BaseModel):
    risk_level: typing.Optional[types.RiskLevel] = None
    risk_score: typing.Optional[float] = None
    action: typing.Optional[types.RecommendedAction] = None
    reason: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    risk_factors: typing.List[str]

class OwnerContext(BaseModel):
    previous_ticket_count: typing.Optional[int] = None
    account_age_days: typing.Optional[int] = None
    last_ticket_date: typing.Optional[str] = None
    avg_resolution_time_hours: typing.Optional[float] = None
    tier_upgrade_date: typing.Optional[str] = None
    total_api_calls_last_month: typing.Optional[int] = None

class TicketAnalysis(BaseModel):
    priority: typing.Optional[types.Priority] = None
    category: typing.Optional[types.Category] = None
    escalate: typing.Optional[bool] = None
    escalation_reason: typing.Optional[str] = None
    suggested_response_time: typing.Optional[int] = None
    tags: typing.List[str]
    urgency_score: typing.Optional[float] = None
    customer_impact_level: typing.Optional[types.ImpactLevel] = None
    recommended_assignee: typing.Optional[types.AssigneeType] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
