# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def FraudDetection(self, user_id: int,username: str,event_type: str,ip_address: str,user_agent: str,timestamp: str,recent_events: typing.List["types.AuthEvent"],
        baml_options: BamlCallOptions = {},
    ) -> types.FraudAssessment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.FraudDetection(user_id=user_id,username=username,event_type=event_type,ip_address=ip_address,user_agent=user_agent,timestamp=timestamp,recent_events=recent_events,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="FraudDetection", args={
                "user_id": user_id,"username": username,"event_type": event_type,"ip_address": ip_address,"user_agent": user_agent,"timestamp": timestamp,"recent_events": recent_events,
            })
            return typing.cast(types.FraudAssessment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def FraudDetectionGemini(self, user_id: int,username: str,event_type: str,ip_address: str,user_agent: str,timestamp: str,recent_events: typing.List["types.AuthEvent"],
        baml_options: BamlCallOptions = {},
    ) -> types.FraudAssessment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.FraudDetectionGemini(user_id=user_id,username=username,event_type=event_type,ip_address=ip_address,user_agent=user_agent,timestamp=timestamp,recent_events=recent_events,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="FraudDetectionGemini", args={
                "user_id": user_id,"username": username,"event_type": event_type,"ip_address": ip_address,"user_agent": user_agent,"timestamp": timestamp,"recent_events": recent_events,
            })
            return typing.cast(types.FraudAssessment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def TicketEscalation(self, ticket_id: int,title: str,description: str,owner_tier: str,created_at: str,owner_history: types.OwnerContext,
        baml_options: BamlCallOptions = {},
    ) -> types.TicketAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.TicketEscalation(ticket_id=ticket_id,title=title,description=description,owner_tier=owner_tier,created_at=created_at,owner_history=owner_history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="TicketEscalation", args={
                "ticket_id": ticket_id,"title": title,"description": description,"owner_tier": owner_tier,"created_at": created_at,"owner_history": owner_history,
            })
            return typing.cast(types.TicketAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def TicketEscalationGemini(self, ticket_id: int,title: str,description: str,owner_tier: str,created_at: str,owner_history: types.OwnerContext,
        baml_options: BamlCallOptions = {},
    ) -> types.TicketAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.TicketEscalationGemini(ticket_id=ticket_id,title=title,description=description,owner_tier=owner_tier,created_at=created_at,owner_history=owner_history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="TicketEscalationGemini", args={
                "ticket_id": ticket_id,"title": title,"description": description,"owner_tier": owner_tier,"created_at": created_at,"owner_history": owner_history,
            })
            return typing.cast(types.TicketAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))



class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def FraudDetection(self, user_id: int,username: str,event_type: str,ip_address: str,user_agent: str,timestamp: str,recent_events: typing.List["types.AuthEvent"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.FraudAssessment, types.FraudAssessment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="FraudDetection", args={
            "user_id": user_id,"username": username,"event_type": event_type,"ip_address": ip_address,"user_agent": user_agent,"timestamp": timestamp,"recent_events": recent_events,
        })
        return baml_py.BamlSyncStream[stream_types.FraudAssessment, types.FraudAssessment](
          __result__,
          lambda x: typing.cast(stream_types.FraudAssessment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FraudAssessment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def FraudDetectionGemini(self, user_id: int,username: str,event_type: str,ip_address: str,user_agent: str,timestamp: str,recent_events: typing.List["types.AuthEvent"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.FraudAssessment, types.FraudAssessment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="FraudDetectionGemini", args={
            "user_id": user_id,"username": username,"event_type": event_type,"ip_address": ip_address,"user_agent": user_agent,"timestamp": timestamp,"recent_events": recent_events,
        })
        return baml_py.BamlSyncStream[stream_types.FraudAssessment, types.FraudAssessment](
          __result__,
          lambda x: typing.cast(stream_types.FraudAssessment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FraudAssessment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def TicketEscalation(self, ticket_id: int,title: str,description: str,owner_tier: str,created_at: str,owner_history: types.OwnerContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TicketAnalysis, types.TicketAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="TicketEscalation", args={
            "ticket_id": ticket_id,"title": title,"description": description,"owner_tier": owner_tier,"created_at": created_at,"owner_history": owner_history,
        })
        return baml_py.BamlSyncStream[stream_types.TicketAnalysis, types.TicketAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.TicketAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TicketAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def TicketEscalationGemini(self, ticket_id: int,title: str,description: str,owner_tier: str,created_at: str,owner_history: types.OwnerContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TicketAnalysis, types.TicketAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="TicketEscalationGemini", args={
            "ticket_id": ticket_id,"title": title,"description": description,"owner_tier": owner_tier,"created_at": created_at,"owner_history": owner_history,
        })
        return baml_py.BamlSyncStream[stream_types.TicketAnalysis, types.TicketAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.TicketAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TicketAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )


class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def FraudDetection(self, user_id: int,username: str,event_type: str,ip_address: str,user_agent: str,timestamp: str,recent_events: typing.List["types.AuthEvent"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FraudDetection", args={
            "user_id": user_id,"username": username,"event_type": event_type,"ip_address": ip_address,"user_agent": user_agent,"timestamp": timestamp,"recent_events": recent_events,
        }, mode="request")
        return __result__
    def FraudDetectionGemini(self, user_id: int,username: str,event_type: str,ip_address: str,user_agent: str,timestamp: str,recent_events: typing.List["types.AuthEvent"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FraudDetectionGemini", args={
            "user_id": user_id,"username": username,"event_type": event_type,"ip_address": ip_address,"user_agent": user_agent,"timestamp": timestamp,"recent_events": recent_events,
        }, mode="request")
        return __result__
    def TicketEscalation(self, ticket_id: int,title: str,description: str,owner_tier: str,created_at: str,owner_history: types.OwnerContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TicketEscalation", args={
            "ticket_id": ticket_id,"title": title,"description": description,"owner_tier": owner_tier,"created_at": created_at,"owner_history": owner_history,
        }, mode="request")
        return __result__
    def TicketEscalationGemini(self, ticket_id: int,title: str,description: str,owner_tier: str,created_at: str,owner_history: types.OwnerContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TicketEscalationGemini", args={
            "ticket_id": ticket_id,"title": title,"description": description,"owner_tier": owner_tier,"created_at": created_at,"owner_history": owner_history,
        }, mode="request")
        return __result__


class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def FraudDetection(self, user_id: int,username: str,event_type: str,ip_address: str,user_agent: str,timestamp: str,recent_events: typing.List["types.AuthEvent"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FraudDetection", args={
            "user_id": user_id,"username": username,"event_type": event_type,"ip_address": ip_address,"user_agent": user_agent,"timestamp": timestamp,"recent_events": recent_events,
        }, mode="stream")
        return __result__
    def FraudDetectionGemini(self, user_id: int,username: str,event_type: str,ip_address: str,user_agent: str,timestamp: str,recent_events: typing.List["types.AuthEvent"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FraudDetectionGemini", args={
            "user_id": user_id,"username": username,"event_type": event_type,"ip_address": ip_address,"user_agent": user_agent,"timestamp": timestamp,"recent_events": recent_events,
        }, mode="stream")
        return __result__
    def TicketEscalation(self, ticket_id: int,title: str,description: str,owner_tier: str,created_at: str,owner_history: types.OwnerContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TicketEscalation", args={
            "ticket_id": ticket_id,"title": title,"description": description,"owner_tier": owner_tier,"created_at": created_at,"owner_history": owner_history,
        }, mode="stream")
        return __result__
    def TicketEscalationGemini(self, ticket_id: int,title: str,description: str,owner_tier: str,created_at: str,owner_history: types.OwnerContext,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TicketEscalationGemini", args={
            "ticket_id": ticket_id,"title": title,"description": description,"owner_tier": owner_tier,"created_at": created_at,"owner_history": owner_history,
        }, mode="stream")
        return __result__


b = BamlSyncClient(DoNotUseDirectlyCallManager({}))
