# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (6)
# #########################################################################

class AssigneeType(str, Enum):
    TIER1_SUPPORT = "TIER1_SUPPORT"
    TIER2_TECHNICAL = "TIER2_TECHNICAL"
    SECURITY_TEAM = "SECURITY_TEAM"
    BILLING_SPECIALIST = "BILLING_SPECIALIST"
    ENGINEERING_TEAM = "ENGINEERING_TEAM"

class Category(str, Enum):
    SECURITY = "SECURITY"
    INTEGRATION = "INTEGRATION"
    BILLING = "BILLING"
    TECHNICAL = "TECHNICAL"
    GENERAL = "GENERAL"

class ImpactLevel(str, Enum):
    MINIMAL = "MINIMAL"
    MODERATE = "MODERATE"
    SIGNIFICANT = "SIGNIFICANT"
    SEVERE = "SEVERE"

class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class RecommendedAction(str, Enum):
    ALLOW = "ALLOW"
    REQUIRE_2FA = "REQUIRE_2FA"
    BLOCK = "BLOCK"
    RESET_PASSWORD = "RESET_PASSWORD"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

# #########################################################################
# Generated classes (4)
# #########################################################################

class AuthEvent(BaseModel):
    event_type: str
    ip_address: str
    user_agent: str
    timestamp: str
    success: bool

class FraudAssessment(BaseModel):
    risk_level: RiskLevel
    risk_score: float
    action: RecommendedAction
    reason: str
    confidence: float
    risk_factors: typing.List[str]

class OwnerContext(BaseModel):
    previous_ticket_count: int
    account_age_days: int
    last_ticket_date: typing.Optional[str] = None
    avg_resolution_time_hours: float
    tier_upgrade_date: typing.Optional[str] = None
    total_api_calls_last_month: int

class TicketAnalysis(BaseModel):
    priority: Priority
    category: Category
    escalate: bool
    escalation_reason: typing.Optional[str] = None
    suggested_response_time: int
    tags: typing.List[str]
    urgency_score: float
    customer_impact_level: ImpactLevel
    recommended_assignee: AssigneeType

# #########################################################################
# Generated type aliases (0)
# #########################################################################
