# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AuthEvent": types.AuthEvent,
    "stream_types.AuthEvent": stream_types.AuthEvent,

    "types.FraudAssessment": types.FraudAssessment,
    "stream_types.FraudAssessment": stream_types.FraudAssessment,

    "types.OwnerContext": types.OwnerContext,
    "stream_types.OwnerContext": stream_types.OwnerContext,

    "types.TicketAnalysis": types.TicketAnalysis,
    "stream_types.TicketAnalysis": stream_types.TicketAnalysis,


    "types.AssigneeType": types.AssigneeType,

    "types.Category": types.Category,

    "types.ImpactLevel": types.ImpactLevel,

    "types.Priority": types.Priority,

    "types.RecommendedAction": types.RecommendedAction,

    "types.RiskLevel": types.RiskLevel,

}
