# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["AuthEvent","FraudAssessment","OwnerContext","TicketAnalysis",]
        ), enums=set(
          ["AssigneeType","Category","ImpactLevel","Priority","RecommendedAction","RiskLevel",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 6
    # #########################################################################

    @property
    def AssigneeType(self) -> "AssigneeTypeViewer":
        return AssigneeTypeViewer(self)

    @property
    def Category(self) -> "CategoryViewer":
        return CategoryViewer(self)

    @property
    def ImpactLevel(self) -> "ImpactLevelViewer":
        return ImpactLevelViewer(self)

    @property
    def Priority(self) -> "PriorityViewer":
        return PriorityViewer(self)

    @property
    def RecommendedAction(self) -> "RecommendedActionViewer":
        return RecommendedActionViewer(self)

    @property
    def RiskLevel(self) -> "RiskLevelViewer":
        return RiskLevelViewer(self)


    # #########################################################################
    # Generated classes 4
    # #########################################################################

    @property
    def AuthEvent(self) -> "AuthEventViewer":
        return AuthEventViewer(self)

    @property
    def FraudAssessment(self) -> "FraudAssessmentViewer":
        return FraudAssessmentViewer(self)

    @property
    def OwnerContext(self) -> "OwnerContextViewer":
        return OwnerContextViewer(self)

    @property
    def TicketAnalysis(self) -> "TicketAnalysisViewer":
        return TicketAnalysisViewer(self)



# #########################################################################
# Generated enums 6
# #########################################################################

class AssigneeTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("AssigneeType")
        self._values: typing.Set[str] = set([  "TIER1_SUPPORT",  "TIER2_TECHNICAL",  "SECURITY_TEAM",  "BILLING_SPECIALIST",  "ENGINEERING_TEAM",  ])
        self._vals = AssigneeTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "AssigneeTypeValues":
        return self._vals


class AssigneeTypeViewer(AssigneeTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]


class AssigneeTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def TIER1_SUPPORT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("TIER1_SUPPORT"))

    @property
    def TIER2_TECHNICAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("TIER2_TECHNICAL"))

    @property
    def SECURITY_TEAM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SECURITY_TEAM"))

    @property
    def BILLING_SPECIALIST(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("BILLING_SPECIALIST"))

    @property
    def ENGINEERING_TEAM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ENGINEERING_TEAM"))




class CategoryAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Category")
        self._values: typing.Set[str] = set([  "SECURITY",  "INTEGRATION",  "BILLING",  "TECHNICAL",  "GENERAL",  ])
        self._vals = CategoryValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "CategoryValues":
        return self._vals


class CategoryViewer(CategoryAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]


class CategoryValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def SECURITY(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SECURITY"))

    @property
    def INTEGRATION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("INTEGRATION"))

    @property
    def BILLING(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("BILLING"))

    @property
    def TECHNICAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("TECHNICAL"))

    @property
    def GENERAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("GENERAL"))




class ImpactLevelAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ImpactLevel")
        self._values: typing.Set[str] = set([  "MINIMAL",  "MODERATE",  "SIGNIFICANT",  "SEVERE",  ])
        self._vals = ImpactLevelValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ImpactLevelValues":
        return self._vals


class ImpactLevelViewer(ImpactLevelAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]


class ImpactLevelValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def MINIMAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MINIMAL"))

    @property
    def MODERATE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MODERATE"))

    @property
    def SIGNIFICANT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SIGNIFICANT"))

    @property
    def SEVERE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SEVERE"))




class PriorityAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Priority")
        self._values: typing.Set[str] = set([  "LOW",  "MEDIUM",  "HIGH",  "CRITICAL",  ])
        self._vals = PriorityValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "PriorityValues":
        return self._vals


class PriorityViewer(PriorityAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]


class PriorityValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def LOW(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("LOW"))

    @property
    def MEDIUM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MEDIUM"))

    @property
    def HIGH(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("HIGH"))

    @property
    def CRITICAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CRITICAL"))




class RecommendedActionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("RecommendedAction")
        self._values: typing.Set[str] = set([  "ALLOW",  "REQUIRE_2FA",  "BLOCK",  "RESET_PASSWORD",  ])
        self._vals = RecommendedActionValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RecommendedActionValues":
        return self._vals


class RecommendedActionViewer(RecommendedActionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]


class RecommendedActionValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def ALLOW(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ALLOW"))

    @property
    def REQUIRE_2FA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REQUIRE_2FA"))

    @property
    def BLOCK(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("BLOCK"))

    @property
    def RESET_PASSWORD(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("RESET_PASSWORD"))




class RiskLevelAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("RiskLevel")
        self._values: typing.Set[str] = set([  "LOW",  "MEDIUM",  "HIGH",  ])
        self._vals = RiskLevelValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "RiskLevelValues":
        return self._vals


class RiskLevelViewer(RiskLevelAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]


class RiskLevelValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def LOW(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("LOW"))

    @property
    def MEDIUM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MEDIUM"))

    @property
    def HIGH(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("HIGH"))





# #########################################################################
# Generated classes 4
# #########################################################################

class AuthEventAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("AuthEvent")
        self._properties: typing.Set[str] = set([  "event_type",  "ip_address",  "user_agent",  "timestamp",  "success",  ])
        self._props = AuthEventProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "AuthEventProperties":
        return self._props


class AuthEventViewer(AuthEventAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class AuthEventProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def event_type(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("event_type"))

    @property
    def ip_address(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("ip_address"))

    @property
    def user_agent(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("user_agent"))

    @property
    def timestamp(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("timestamp"))

    @property
    def success(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("success"))




class FraudAssessmentAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FraudAssessment")
        self._properties: typing.Set[str] = set([  "risk_level",  "risk_score",  "action",  "reason",  "confidence",  "risk_factors",  ])
        self._props = FraudAssessmentProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FraudAssessmentProperties":
        return self._props


class FraudAssessmentViewer(FraudAssessmentAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class FraudAssessmentProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def risk_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("risk_level"))

    @property
    def risk_score(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("risk_score"))

    @property
    def action(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("action"))

    @property
    def reason(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("reason"))

    @property
    def confidence(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("confidence"))

    @property
    def risk_factors(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("risk_factors"))




class OwnerContextAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("OwnerContext")
        self._properties: typing.Set[str] = set([  "previous_ticket_count",  "account_age_days",  "last_ticket_date",  "avg_resolution_time_hours",  "tier_upgrade_date",  "total_api_calls_last_month",  ])
        self._props = OwnerContextProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "OwnerContextProperties":
        return self._props


class OwnerContextViewer(OwnerContextAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class OwnerContextProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def previous_ticket_count(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("previous_ticket_count"))

    @property
    def account_age_days(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("account_age_days"))

    @property
    def last_ticket_date(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("last_ticket_date"))

    @property
    def avg_resolution_time_hours(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("avg_resolution_time_hours"))

    @property
    def tier_upgrade_date(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tier_upgrade_date"))

    @property
    def total_api_calls_last_month(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("total_api_calls_last_month"))




class TicketAnalysisAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("TicketAnalysis")
        self._properties: typing.Set[str] = set([  "priority",  "category",  "escalate",  "escalation_reason",  "suggested_response_time",  "tags",  "urgency_score",  "customer_impact_level",  "recommended_assignee",  ])
        self._props = TicketAnalysisProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "TicketAnalysisProperties":
        return self._props


class TicketAnalysisViewer(TicketAnalysisAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)


    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class TicketAnalysisProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821



    @property
    def priority(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("priority"))

    @property
    def category(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("category"))

    @property
    def escalate(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("escalate"))

    @property
    def escalation_reason(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("escalation_reason"))

    @property
    def suggested_response_time(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("suggested_response_time"))

    @property
    def tags(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("tags"))

    @property
    def urgency_score(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("urgency_score"))

    @property
    def customer_impact_level(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("customer_impact_level"))

    @property
    def recommended_assignee(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("recommended_assignee"))
