name: Dagger Fraud Simulation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-fraud-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dagger CLI
        uses: dagger/dagger-for-github@v7
        with:
          version: "0.19.8"
          install-only: true
      - name: Run Dagger Pipeline (Cloud)
        run: |
          dagger run --cloud authentication-service/auth-service:fraud-v1 \
            call run-fraud-sim \
            --gemini-api-key env:GEMINI_API_KEY \
            --groq-api-key env:GROQ_API_KEY
